### ISSUE TITLE
ldd not finding libqgtk2 platform theme.

### ISSUE THREAD

**Issue by azagaya** [probonopd/linuxdeployqt#350]
Hi,
This may be related to #338.
I have an Ubuntu Trusty just for building Appimages, and i've installed Qt 5.12 there. However, when running linuxdeployqt, i have this:

> ERROR: findDependencyInfo: "ldd: /opt/Qt/5.12.1/gcc_64/plugins/platformthemes/libqgtk2.so: No such file or directory\n"
ERROR: getBinaryRPaths: "objdump: '/opt/Qt/5.12.1/gcc_64/plugins/platformthemes/libqgtk2.so': No such file\n"
ERROR: file copy failed from "/opt/Qt/5.12.1/gcc_64/plugins/platformthemes/libqgtk2.so"
ERROR:  to "/home/pablo/QtWorkspace/Appimages/NormalmapGenerator/usr/bin/..//plugins/platformthemes/libqgtk2.so"
ERROR: findDependencyInfo: "ldd: /opt/Qt/5.12.1/gcc_64/plugins/styles/libqgtk2style.so: No such file or directory\n"
ERROR: getBinaryRPaths: "objdump: '/opt/Qt/5.12.1/gcc_64/plugins/styles/libqgtk2style.so': No such file\n"
ERROR: file copy failed from "/opt/Qt/5.12.1/gcc_64/plugins/styles/libqgtk2style.so"
ERROR:  to "/home/pablo/QtWorkspace/Appimages/NormalmapGenerator/usr/bin/..//plugins/styles/libqgtk2style.so"
ERROR: ldd outputLine: "libXrender.so.1 => not found"
ERROR: for binary: "/opt/Qt/5.12.1/gcc_64/plugins/platforms/libqxcb.so"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.

How can i fix this? should i use older Qt??

**Comment by probonopd** [comment]
Thanks for reporting. Where is your Qt 5.12.1 coming from? Where is your `libqgtk2style.so` coming from?

**Comment by azagaya** [comment]
Hi,
I've installed everything with the online installer provided in Qt website. I think libqtgtk2style was not even installed that way.

**Comment by dxsooo** [comment]
Hi, I had the same problem when I use linuxdeployqt 6. I built my Qt 5.9.7 in docker and it won't build libqtgtk2style.so. When I checked my downloaded Qt(5.9.2) that works well with older linuxdeployqt 5, it doesn't have libqtgtk2style.so neither.

I suppose the newest linuxdeployqt searching wrong *.so?

**Comment by probonopd** [comment]
How exactly are you invoking `linuxdeployqt` @azagaya? Are you using some command line options?

**Comment by azagaya** [comment]
Hi,
I'm using -qmake and -appimage switches only.

**Comment by probonopd** [comment]
Does the file `/opt/Qt/5.12.1/gcc_64/plugins/platformthemes/libqgtk2.so` exist on your system? Or similar files?

**Comment by probonopd** [comment]
If it does not exist yet, what happens if you do 

```
apt-get update
apt-get -y install libgtk2.0-dev
git clone http://code.qt.io/qt/qtstyleplugins.git
cd qtstyleplugins
qmake
make -j$(nproc)
sudo make install 
cd -
```

before invoking `linuxdeployqt`?

**Comment by azagaya** [comment]
No, only gtk3 versions seems to be installed with newer Qt.. . Funny thing is that I did not have this problem last year

**Comment by probonopd** [comment]
Please try the commands I have shown above and let us know whether this resolves it. Thanks.

**Comment by probonopd** [comment]
Please see whether this version resolves it:
https://transfer.sh/RxJ08/linuxdeployqt-continuous-x86_64.AppImage

**Comment by azagaya** [comment]
Thanks! As soon as I get home after work I'll try!

**Comment by azagaya** [comment]
With that version i get this warning:

> The plugin "/opt/Qt5.12.1/5.12.1/gcc_64/plugins/platformthemes/libqgtk2.so" could not be found. Please check spelling and try again!

However, Appimage generated works in my pc.
I have not tryied compiling qt styles myself yet, should i try that also? or this version should resolve it by itself?

**Comment by probonopd** [comment]
Thanks for testing. If you want it to look properly, you still should do

https://github.com/probonopd/linuxdeployqt/issues/350#issuecomment-466661065

**Comment by b00f** [comment]
I also have the same issue. Any way to resolve it?

**Comment by b00f** [comment]
Unfortunately I was wrong. I got Segmentation fault error. At fist place I thought it's my mistake but looks like it was not. Please let me if you can find a workaround.

**Comment by probonopd** [comment]
Please try https://github.com/probonopd/linuxdeployqt/issues/355#issuecomment-471228074. The segfault may be unrelated to the gtk warnings.

**Comment by ibXCM** [comment]
> git clone http://code.qt.io/qt/qtstyleplugins.git

Thanks bro，you solved my problem。

**Comment by bohning** [comment]
Unfortunately, compilation of the qtstyleplugins with gtk2.0 fails and I get:

```
qgtkstyle_p.cpp:511:11: error: ‘setSystemPalette’ is not a member of ‘QApplicationPrivate’
           QApplicationPrivate::setSystemPalette(newPalette);
           ^
Makefile:1915: recipe for target '.obj/qgtkstyle_p.o' failed
```

where this seems to be the solution: https://forums.freebsd.org/threads/qt5-style-plugins-patch-to-install-with-qt-5-15-0.76084/

So obviously, setSystemPalette() moved from QApplicationPrivate:: to QApplication:: namespace.

Any ideas?

**Comment by probonopd** [comment]
@bohning which system are you compiling this on? And using which Qt version from where?

**Comment by bohning** [comment]
@probonopd This was on Appveyor CI, Ubuntu 16.04, pre-installed Qt 5.15.2.

See the console output [here](https://ci.appveyor.com/project/bohning/ultrastar-creator/builds/37275340/job/ve2uhi7quwqat03m).

Thanks for your response and taking the time.

**Comment by probonopd** [comment]
Are you using the 5.15.2 source code for qtstyleplugins?

**Comment by bohning** [comment]
Ah, now I see the problem. I simply followed [your](https://github.com/probonopd/linuxdeployqt/issues/350#issuecomment-466661065) proposed solution and this is probably wrong. How would I get the 5.15.2 source code of the qtstyleplugins on AppVeyor?

**Comment by probonopd** [comment]
Err, looking at https://code.qt.io/cgit/qt/qtstyleplugins.git/ there seem to have been no changes in years, so that's probably not the issue. Sorry! Maybe it doesn't compile on 5.15.2 anymore? Can you try with e.g., Qt 5.9, just to be sure?

**Comment by bohning** [comment]
Yes, that’s where I just looked and came to the same conclusion. With Qt 5.9 it compiles just fine.

**Comment by probonopd** [comment]
Sounds like an issue with qtstyleplugins then? Maybe you'd like to open an issue at https://bugreports.qt.io/?

**Comment by gaojinhsu** [comment]
> 
error occurs when try to run `make -j$(nproc)`

Makefile:1575: recipe for target '.obj/qgtkstyle.o' failed
make[4]: *** [.obj/qgtkstyle.o] Error 1
make[4]: *** Waiting for unfinished jobs....
qgtkstyle_p.cpp: In member function ‘void QGtkStyleUpdateScheduler::updateTheme()’:
qgtkstyle_p.cpp:511:32: error: ‘setSystemPalette’ is not a member of ‘QApplicationPrivate’
           QApplicationPrivate::setSystemPalette(newPalette);
                                ^~~~~~~~~~~~~~~~
Makefile:1861: recipe for target '.obj/qgtkstyle_p.o' failed
make[4]: *** [.obj/qgtkstyle_p.o] Error 1
make[4]: Leaving directory '/home/greysongjxu/Desktop/build-qt5testdemo-Desktop-Release/AppDir/qtstyleplugins/src/plugins/styles/gtk2'
Makefile:150: recipe for target 'sub-gtk2-make_first' failed
make[3]: *** [sub-gtk2-make_first] Error 2
make[3]: Leaving directory '/home/greysongjxu/Desktop/build-qt5testdemo-Desktop-Release/AppDir/qtstyleplugins/src/plugins/styles'
Makefile:72: recipe for target 'sub-styles-make_first' failed
make[2]: *** [sub-styles-make_first] Error 2
make[2]: Leaving directory '/home/greysongjxu/Desktop/build-qt5testdemo-Desktop-Release/AppDir/qtstyleplugins/src/plugins'
Makefile:46: recipe for target 'sub-plugins-make_first' failed
make[1]: *** [sub-plugins-make_first] Error 2
make[1]: Leaving directory '/home/greysongjxu/Desktop/build-qt5testdemo-Desktop-Release/AppDir/qtstyleplugins/src'
Makefile:46: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
