### ISSUE TITLE
Build from source breaks after upgrade from Qt 6.4.3 to 6.5.0

### ISSUE THREAD

**Issue by petrmanek** [probonopd/linuxdeployqt#584]
I discovered that upgrading Qt from version 6.4.3 to 6.5.0 (or later) breaks the build from source. The main symptom are the following qmake messages:

```
$ qmake6
/tmp/linuxdeployqt/.qmake.conf:1: Cannot find feature qt_build_config
/tmp/linuxdeployqt/.qmake.conf:1: Cannot find feature qt_build_config
Info: creating stash file /tmp/linuxdeployqt/.qmake.stash
/tmp/linuxdeployqt/linuxdeployqt.pro:1: Cannot find feature qt_parts
```

Curiously these only appear as "warnings" because qmake still terminates with exit code 0. In my CI, this led to a failing attempt to invoke GNU make, which had the following predictable output since no objects for executable targets were registered:

```
$ make
g++ -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib -o linuxdeployqt     /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: linuxdeployqt] Error 1
```

I suspect that the cause may have something to do with the way makespecs are organized in Qt 6.4 and 6.5. However, I do not really understand qmake internals all that well.

For now I am mitigating this by sticking with Qt 6.4.3 but it would be nice to be able to use version 6.5 at some point since it is a LTS release, which brings many features that are not present in 6.4.

**Comment by probonopd** [comment]
Are you building linuxdeployqt from source? What happens if you use the linuxdeployqt AppImage (continuous build) provided on GitHub Releases?

**Comment by petrmanek** [comment]
> Are you building linuxdeployqt from source?

Yes, I am building linuxdeployqt from source using clang++ 10 with Qt 6.5 under dockerized Ubuntu Focal inside my CI.


> What happens if you use the linuxdeployqt AppImage (continuous build) provided on GitHub Releases?

The published AppImage works without any issues. The drawback is that it is only provided for the x86_64 (amd64) CPU architecture. The reason I was building linuxdeployqt from source in the first place is to support other architectures such as aarch64 (arm64) and armv7 (arm32) in my CI. That being said, the symptoms described in this bug report are present for all CPU architectures with Qt 6.5. I can even reproduce it on my x86_64 laptop with Qt 6.5.2.

**Comment by probonopd** [comment]
This probably is because linuxdeployqt has never really been ported to Qt6. It is a Qt5 application and has only ever been tested to be compiled with Qt5.

**Comment by petrmanek** [comment]
> This probably is because linuxdeployqt has never really been ported to Qt6. It is a Qt5 application and has only ever been tested to be compiled with Qt5.

While that is certainly possible, I suspect that this is merely caused by change of qmake's configuration language. Out of curiosity, I tried running it in project generation mode using `qmake6 -project`, and got somewhat sane .pro file out of it. The only drawback was that I had to manually cherry-pick files that belong to tests and examples. You may want to consider it in a future release/PR.

**Comment by berleant** [comment]
@petrmanek 

> I tried running it in project generation mode using qmake6 -project, and got somewhat sane .pro file out of it. The only drawback was that I had to manually cherry-pick files that belong to tests and examples. 

Do you happen to still have the result of that process on hand?

**Comment by petrmanek** [comment]
> Do you happen to still have the result of that process on hand?

Unfortunately not, but I tried replicating my experiment and attach the auto-generated .pro file, as provided by `qmake6 -project`: [linuxdeployqt.pro.txt](https://github.com/user-attachments/files/19226880/linuxdeployqt.pro.txt) (I added the .txt extension otherwise GitHub would not let me select it)


> Edit: Found that using `cmake` works just fine (e.g. `cd build && cmake -DCMAKE_PREFIX_PATH=/opt/Qt/6.8.1/lib/cmake ../`)

I can confirm that with Qt v6.8.2, gcc v14.2.1 and cmake v3.31.6 the current HEAD of the repository (04480557d24c9d0d45f1f27f9ac1b8f1387d1d26) configures and compiles successfully. I can only see the following warning:

```
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
```
